/-
  # AKS Sorting Network — Root Module

  Imports all modules. For the main results, see:
  • `AKS/Seiferas.lean` — Seiferas (2009) separator-based O(n log n) sorting networks
  • `AKS/Bounds/Asymptotic.lean` — improved local-project minimum-depth limsup bound
-/

import AKS.Sort.Defs
import AKS.Sort.Monotone
import AKS.Sort.ZeroOne
import AKS.Sort.Depth
import AKS.Sort.Shrink
import AKS.Sort.Perm
import AKS.Sort.Displaced
import AKS.Sort.Bipartite
import AKS.Bitonic.Defs
import AKS.Bitonic.Depth
import AKS.Bitonic.LayerExec
import AKS.Bitonic.Bitonic01
import AKS.Bitonic.CompareLayer
import AKS.Bitonic.Correctness
import AKS.Bitonic.Shrink
import AKS.Misc.Fin
import AKS.Misc.Floor
import AKS.Misc.Log
import AKS.Halver.Defs
import AKS.Halver.Empty
import AKS.Halver.Mono
import AKS.Halver.MatchingCount
import AKS.Halver.Paterson
import AKS.Halver.PatersonCorrectness
import AKS.Halver.PatersonExistence
import AKS.Halver.PatersonEntropy
import AKS.Halver.PatersonMonotonicity
import AKS.Halver.PatersonDepthBridge
import AKS.Halver.PatersonWitnesses
import AKS.Halver.PatersonCollapsedWitnesses
import AKS.Halver.PatersonTail
import AKS.Halver.PatersonFull
import AKS.Halver.PatersonSimultaneous
import AKS.Halver.PatersonJointTail
import AKS.Separator.PatersonInjective
import AKS.Separator.PatersonDefs
import AKS.Separator.PatersonFamily
import AKS.Separator.PatersonConstruction
import AKS.Separator.PatersonNear
import AKS.Separator.PatersonStep
import AKS.Separator.PatersonPrefix
import AKS.Separator.PatersonCertificate
import AKS.Separator.PatersonGood
import AKS.Paterson.BagParams
import AKS.Paterson.Rounding
import AKS.Paterson.LatticeRounding
import AKS.Paterson.RankTransfer
import AKS.Paterson.GoodRouting
import AKS.Paterson.Interior
import AKS.Separator.PatersonOdd
import AKS.Separator.PatersonFlip
import AKS.Separator.PatersonOddFinal
import AKS.Halver.Tanner
import AKS.Halver.FromExpander
import AKS.Konig.Defs
import AKS.Konig.Hall
import AKS.Konig.Coloring
import AKS.Konig.ContractedBipartite
import AKS.Konig.Matching
import AKS.Separator.Defs
import AKS.Separator.Family
import AKS.Separator.Provider
import AKS.Separator.PatersonProvider
import AKS.Separator.FromHalverDefs
import AKS.Separator.FromHalver
import AKS.Separator.General
import AKS.Separator.SepProof
import AKS.Separator.Axioms
import AKS.Halver.Quotient
import AKS.Halver.General
import AKS.Halver.Axioms
import AKS.Bags.Params
import AKS.Bags.PatersonParams
import AKS.Bags.PatersonNumerics
import AKS.Halver.PatersonAxioms
import AKS.Bags.Defs
import AKS.Bags.Network
import AKS.Bags.SplitCard
import AKS.Bags.Sizes
import AKS.Bags.Filter
import AKS.Bags.SepBridge
import AKS.Bags.Subtree
import AKS.Bags.Source3
import AKS.Bags.Strange
import AKS.Bags.Sorts
import AKS.Bags.Depth
import AKS.MGG.Defs
import AKS.MGG.DFT
import AKS.MGG.WalkExpansion
import AKS.MGG.YoungDefs
import AKS.MGG.Young
import AKS.MGG.YoungAssembly
import AKS.MGG.Spectral
import AKS.MGG.Axioms
import AKS.Graph.Regular
import AKS.Graph.Square
import AKS.Graph.Complete
import AKS.Graph.Graph
import AKS.Graph.Walk
import AKS.Graph.Contract
import AKS.Graph.Kronecker
import AKS.Halver.Mixing
import AKS.ZigZag.Operators
import AKS.ZigZag.Spectral
import AKS.ZigZag.RVWInequality
import AKS.ZigZag.RVWBound
import AKS.ZigZag.Expanders
import AKS.Seiferas
import AKS.Bounds.Upper
import AKS.Bounds.Asymptotic
import AKS.Bounds.Axioms
import AKS.Bounds.Paterson
import AKS.Bounds.PatersonAxioms
import AKS.Bitonic.TightDepth
import AKS.Paterson.BagSeparator
import AKS.Paterson.Stage
import AKS.Paterson.FastParams
import AKS.Paterson.Fresh
import AKS.Paterson.Subtree
import AKS.Paterson.Balance
import AKS.Paterson.Transition
import AKS.Paterson.Schedule
import AKS.Paterson.Root
import AKS.Paterson.Accounting
import AKS.Paterson.Padding
import AKS.Paterson.Axioms
import AKS.Separator.PatersonRefinement
import AKS.Separator.PatersonPartial
